### PR TITLE
Upgrade civix from 22.05.2 to 23.02.1 (smarty v3 compliance)

### PR DESCRIPTION
**Pull request by VangelisP**
Related issue: #120 

Doubts:
The initial upgrade via `civix` tried to cleanup/remove the following mixin files:
* `mixin/ang-php@1.0.0.mixin.php`
* `mixin/menu-xml@1.0.0.mixin.php`
* `mixin/mgd-php@1.0.0.mixin.php`
* `mixin/polyfill.php`
* `mixin/setting-php@1.0.0.mixin.php`

which I've reverted and kept them in the `mixin` folder. Not sure how valid they are as I've tested it with both cases (with and without those files) and it did work properly in both situations.

### CODE REVIEW

**Comment by jensschuppe** [comment]
I added this to the (closed) `2.1` milestone, as `2.2` seems to be far ahead and this is a minor fix for a patch-level version on the `2.1` version branch, IMO.

**Comment by jensschuppe** [comment]
*Civix* removing mixins is correct, as they are part of CiviCRM Core (see e.g. https://github.com/civicrm/civicrm-core/commit/a323ce8a98e43f501ac5b3d114ab37b34046ce68) for the relevant version (`5.45` as stated in the `info.xml`), so they can be safely left removed.

**Review by bjendres — COMMENTED** [review]
Does that affect the minimum CiviCRM version (currently ``5.45``)?

**Comment by jensschuppe** [comment]
No, the mixins are part of Core since `5.45`, that's what I was trying to say … and if they weren't, *Civix* would adjust the minimum version in the `info.xml`, so this would be visible.

**Comment by VangelisP** [comment]
Thanks @jensschuppe , I've reworked the patch and forced-pushed it.

**Comment by VangelisP** [comment]
Shall we merge this one or you need time to review from your side? 

I can confirm that it works as expected from our side

**Comment by jensschuppe** [comment]
@bjendres This is planned for the `2.1` milestone, so this will have to be cherry-picked into a new `2.1.x` branch.

Also, *Civix* would've adjusted the minimal required CiviCRM Core version if there was a change needed.

**Comment by VangelisP** [comment]
I agree with @jensschuppe on the versioning part, it would be taken care by civix. Since it didn't, all is good.

**Pull request merged**
