### PR TITLE
Add flexible backend and UI 2.0

### PR DESCRIPTION
**Pull request by pfigel**
*WIP*

- [ ] Add pre-upgrade backup of `civicrm_sqltasks` table
- [ ] Drop unused columns (`main_sql`, `post_sql`)
- [ ] Move upgraders to a single `upgrade_0200` method
- [ ] Apply changes from `release/1.x`
- [ ] Update docs

### CODE REVIEW

**Comment by magnolia61** [comment]
From an implementer perspective very much interested in this development. Would it be possible to open an issues about this PR with the idea and possible screenshots. Would you be helped with testing & feedback?

**Comment by bjendres** [comment]
Sure, @magnolia61. There might also be a case in developing this (massive) overhaul in a branch on the repo instead of a PR. What do you think @pfigel?

**Comment by magnolia61** [comment]
> 
> 
> Sure, @magnolia61. There might also be a case in developing this (massive) overhaul in a branch on the repo instead of a PR. What do you think @pfigel?
;-)

**Comment by magnolia61** [comment]
;-)

**Comment by magnolia61** [comment]
Good morning, I've asked before. Would like to try out this new iteration. Could you make this into an alpha release or a different branch to make it easier to help test. Cheers and happy easter, Richard

**Comment by pfigel** [comment]
@magnolia61 sorry for replying so late - we have some tagged versions based on this over on our fork, [this](https://github.com/greenpeace-cee/de.systopia.sqltasks/releases/tag/v2.0-beta.gp.20) would be the latest. We haven't tested the upgrade path for more recent versions of upstream (we diverged about 2 years ago), so no promises on whether that will work currently. 😅

I do plan on working on this and hopefully getting things merged during the Berlin sprint next month, so hopefully we'll have an official alpha release after that.

**Comment by pfigel** [comment]
Closing in favour of #94

**Pull request closed without merging**
