### PR TITLE
Advanced Scheduler for Tasks

### PR DESCRIPTION
**Pull request by sluc23**
Add advanced scheduler for Tasks, to be executed in specific date/time regularly

### CODE REVIEW

**Comment by pfigel** [comment]
We started testing this, and so far it seems our use-cases quite nicely, so thanks @sluc23!

While testing the scheduler we found a bug where `strtotime` was applied to dates twice, fix can be found [here.](https://github.com/systopia/de.systopia.sqltasks/commit/53d4cc54d1e9013c598c7759e3dbab07ae608610)

Will report back when we've finished testing.

**Comment by bjendres** [comment]
rebased and merged to ``dev_56``

**Comment by bjendres** [comment]
is now in ``master``, with a minor cosmetic change. Thanks @sluc23 !

**Comment by pfigel** [comment]
@bjendres we made some fixes for this in https://github.com/greenpeace-cee/de.systopia.sqltasks/tree/fix-advanced-scheduler, e259a996e179430d37e4ef979fcf1777636fa771 and cfffc9b68f311092fb8441f8af60a9564eda8d07 (this one could be considered a small change in behaviour).

**Comment by bjendres** [comment]
@patf: Thanks for the head's up, but I get a lot of conflicts with these two commits, maybe you could create a PR, or talk me through them tomorrow?

**Comment by pfigel** [comment]
@bjendres I cherry-picked to a new branch based on your master here: https://github.com/systopia/de.systopia.sqltasks/pull/59

**Comment by bjendres** [comment]
Thanks @pfigel, Idk why I did get conflicts when I tried that... Must've done something stupid... Thanks!

**Pull request merged**
